import { useRef, useState } from 'react'
import {
  motion,
  useScroll,
  useTransform,
  useMotionValueEvent,
  useReducedMotion,
} from 'framer-motion'
import { useTheme } from '../../contexts/ThemeContext'
import {
  AlertTriangle, GitBranch, Shield, Building2,
  TrendingDown, Users, AlertCircle, X, RefreshCw, XCircle,
} from 'lucide-react'

// ─── helpers ──────────────────────────────────────────────────────────────────
const cv = (n, op = 1) =>
  op < 1 ? `rgb(var(--c-dark-${n}) / ${op})` : `rgb(var(--c-dark-${n}))`

const EASE = [0.25, 0.4, 0.25, 1]
const CARD_W     = 480   // px — desktop card width
const CARD_GAP   = 32    // px — gap between cards
const CARD_STRIDE = CARD_W + CARD_GAP

// ─── Problem data ─────────────────────────────────────────────────────────────
const PROBLEMS = [
  {
    Icon: AlertTriangle,
    num: '01',
    title: 'Manual Certificate Generation',
    desc: 'Hundreds of certificates generated by hand after every examination cycle, wasting days of staff time with zero scalability.',
    color: 'text-red-400',
    accent: '#f87171',
    glowD: 'rgba(239,68,68,0.2)',   glowL: 'rgba(239,68,68,0.1)',
    borderD: 'rgba(239,68,68,0.5)', borderL: 'rgba(239,68,68,0.3)',
    bgAccentD: 'rgba(239,68,68,0.07)', bgAccentL: 'rgba(239,68,68,0.04)',
  },
  {
    Icon: GitBranch,
    num: '02',
    title: 'Multiple Disconnected Systems',
    desc: 'Spreadsheets, email threads, and separate tools patched together with no single source of truth — causing constant data loss.',
    color: 'text-orange-400',
    accent: '#fb923c',
    glowD: 'rgba(249,115,22,0.2)',  glowL: 'rgba(249,115,22,0.1)',
    borderD: 'rgba(249,115,22,0.5)',borderL: 'rgba(249,115,22,0.3)',
    bgAccentD: 'rgba(249,115,22,0.07)', bgAccentL: 'rgba(249,115,22,0.04)',
  },
  {
    Icon: Shield,
    num: '03',
    title: 'Exam Cheating & Security Risks',
    desc: 'No proctoring, weak session authentication, and shared answer keys make every result questionable and legally indefensible.',
    color: 'text-red-500',
    accent: '#ef4444',
    glowD: 'rgba(239,68,68,0.2)',   glowL: 'rgba(239,68,68,0.1)',
    borderD: 'rgba(239,68,68,0.5)', borderL: 'rgba(239,68,68,0.3)',
    bgAccentD: 'rgba(239,68,68,0.07)', bgAccentL: 'rgba(239,68,68,0.04)',
  },
  {
    Icon: Building2,
    num: '04',
    title: 'No Organization Management',
    desc: 'Unable to manage multiple departments, branches, or client organizations from a single platform — every client is a separate headache.',
    color: 'text-amber-400',
    accent: '#fbbf24',
    glowD: 'rgba(245,158,11,0.2)',  glowL: 'rgba(245,158,11,0.1)',
    borderD: 'rgba(245,158,11,0.5)',borderL: 'rgba(245,158,11,0.3)',
    bgAccentD: 'rgba(245,158,11,0.07)', bgAccentL: 'rgba(245,158,11,0.04)',
  },
  {
    Icon: TrendingDown,
    num: '05',
    title: 'Zero Actionable Analytics',
    desc: 'No visibility into pass rates, score trends, or candidate performance — decisions made on gut feel, not data.',
    color: 'text-orange-500',
    accent: '#f97316',
    glowD: 'rgba(249,115,22,0.2)',  glowL: 'rgba(249,115,22,0.1)',
    borderD: 'rgba(249,115,22,0.5)',borderL: 'rgba(249,115,22,0.3)',
    bgAccentD: 'rgba(249,115,22,0.07)', bgAccentL: 'rgba(249,115,22,0.04)',
  },
  {
    Icon: Users,
    num: '06',
    title: 'Poor Candidate Experience',
    desc: 'Confusing registration, indefinitely delayed results, and no self-service certificate portal drive candidates away for good.',
    color: 'text-red-400',
    accent: '#f87171',
    glowD: 'rgba(239,68,68,0.2)',   glowL: 'rgba(239,68,68,0.1)',
    borderD: 'rgba(239,68,68,0.5)', borderL: 'rgba(239,68,68,0.3)',
    bgAccentD: 'rgba(239,68,68,0.07)', bgAccentL: 'rgba(239,68,68,0.04)',
  },
]

const HEADING_LINES = [
  ['Managing', ' ', 'Online', ' ', 'Exams'],
  ["Shouldn't", ' ', 'Be', ' ', 'This', ' ', 'Difficult.'],
]
const P_GRAD_WORDS = new Set(['Online', 'Exams', 'Difficult.'])

const probGradStyle = {
  background: 'linear-gradient(135deg,#fb923c 0%,#ef4444 55%,#dc2626 100%)',
  backgroundSize: '200% 100%',
  WebkitBackgroundClip: 'text',
  WebkitTextFillColor: 'transparent',
  backgroundClip: 'text',
}

// ─── Motion variants ──────────────────────────────────────────────────────────
const charVar = {
  hidden:  { opacity: 0, y: 16, filter: 'blur(4px)' },
  visible: { opacity: 1, y: 0,  filter: 'blur(0px)',
    transition: { duration: 0.3, ease: EASE } },
}
const headingStagger = {
  hidden:  {},
  visible: { transition: { staggerChildren: 0.022, delayChildren: 0.2 } },
}
const fadeUp = (delay = 0) => ({
  initial:     { opacity: 0, y: 20, filter: 'blur(6px)' },
  whileInView: { opacity: 1, y: 0,  filter: 'blur(0px)' },
  viewport:    { once: true, margin: '-40px' },
  transition:  { duration: 0.55, delay, ease: EASE },
})

// ─── BackgroundGlow ───────────────────────────────────────────────────────────
function BackgroundGlow({ isDark, accentColor }) {
  const gridC = isDark ? 'rgba(239,68,68,0.025)' : 'rgba(239,68,68,0.04)'
  return (
    <div aria-hidden="true" className="absolute inset-0 overflow-hidden pointer-events-none">
      <div className="absolute inset-0" style={{
        backgroundImage: `linear-gradient(${gridC} 1px,transparent 1px),linear-gradient(90deg,${gridC} 1px,transparent 1px)`,
        backgroundSize: '64px 64px',
      }} />
      <motion.div
        className="absolute rounded-full"
        animate={{ background: `radial-gradient(circle,${accentColor} 0%,transparent 70%)` }}
        transition={{ duration: 0.8 }}
        style={{ width: 800, height: 800, top: '5%', left: '50%', transform: 'translateX(-50%)' }}
      />
      <div className="absolute inset-0 opacity-[0.02]" style={{
        backgroundImage: 'url("data:image/svg+xml,%3Csvg viewBox=\'0 0 256 256\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'n\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.9\' numOctaves=\'4\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23n)\'/%3E%3C/svg%3E")',
        backgroundSize: '180px 180px',
      }} />
    </div>
  )
}

// ─── SectionHeader ────────────────────────────────────────────────────────────
function SectionHeader({ isDark }) {
  const badgeStyle = isDark
    ? { background: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.25)', color: '#fca5a5' }
    : { background: 'rgba(239,68,68,0.06)', border: '1px solid rgba(239,68,68,0.2)',  color: '#dc2626' }

  return (
    <div className="text-center mb-16 px-4">
      <motion.div
        initial={{ opacity: 0, y: -14, filter: 'blur(6px)' }}
        whileInView={{ opacity: 1, y: 0,   filter: 'blur(0px)' }}
        viewport={{ once: true }}
        transition={{ duration: 0.5, ease: EASE }}
        className="mb-6"
      >
        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-sm font-medium"
          style={{ backdropFilter: 'blur(12px)', ...badgeStyle }}>
          <AlertTriangle className="w-3.5 h-3.5" />
          <span>Challenges</span>
          <motion.span className="w-1.5 h-1.5 rounded-full bg-red-400"
            animate={{ opacity: [1, 0.2, 1] }}
            transition={{ duration: 1.4, repeat: Infinity }}
            aria-hidden="true" />
        </div>
      </motion.div>

      <motion.h2
        id="problem-heading"
        variants={headingStagger}
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true }}
        className="text-4xl sm:text-5xl lg:text-[52px] font-extrabold leading-[1.1] tracking-tight mb-5 text-white"
      >
        {HEADING_LINES.map((words, li) => (
          <span key={li} className="block">
            {words.map((word, wi) => {
              if (word === ' ')
                return <span key={wi} style={{ display: 'inline-block', width: '0.28em' }} aria-hidden="true" />
              if (P_GRAD_WORDS.has(word)) {
                return (
                  <motion.span key={wi} variants={charVar} style={{ display: 'inline-block' }}>
                    <motion.span
                      style={probGradStyle}
                      animate={{ backgroundPosition: ['0% 50%', '100% 50%', '0% 50%'] }}
                      transition={{ duration: 5, repeat: Infinity, ease: 'linear', delay: li * 0.5 }}
                    >{word}</motion.span>
                  </motion.span>
                )
              }
              return (
                <span key={wi} className="inline-block">
                  {word.split('').map((ch, ci) => (
                    <motion.span key={ci} variants={charVar} style={{ display: 'inline-block' }}>{ch}</motion.span>
                  ))}
                </span>
              )
            })}
          </span>
        ))}
      </motion.h2>

      <motion.p {...fadeUp(0.45)} className="text-base text-dark-400 leading-relaxed max-w-xl mx-auto">
        Many organizations still struggle with disconnected tools, manual certificate
        generation, weak security, poor candidate experience, and limited reporting —
        costing time, trust, and credibility.
      </motion.p>
    </div>
  )
}

// ─── HorizontalCard (desktop) ─────────────────────────────────────────────────
function HorizontalCard({ problem, isActive, isDark }) {
  const { Icon, num, title, desc, color, accent, glowD, glowL, borderD, borderL, bgAccentD, bgAccentL } = problem
  const glow   = isDark ? glowD   : glowL
  const border = isDark ? borderD : borderL
  const bgAcc  = isDark ? bgAccentD : bgAccentL

  return (
    <motion.div
      animate={{
        scale:   isActive ? 1 : 0.88,
        opacity: isActive ? 1 : 0.3,
      }}
      transition={{ duration: 0.5, ease: EASE }}
      className="shrink-0 flex flex-col rounded-3xl p-8"
      style={{
        width:          CARD_W,
        minHeight:      300,
        background:     isActive ? bgAcc : cv(900, 0.5),
        border:         `1px solid ${isActive ? border : cv(700, 0.12)}`,
        backdropFilter: 'blur(20px)',
        boxShadow:      isActive
          ? `0 24px 80px rgba(0,0,0,${isDark ? 0.55 : 0.12}),0 0 60px ${glow},inset 0 1px 0 rgba(255,255,255,${isDark ? 0.07 : 0.5})`
          : `0 4px 20px rgba(0,0,0,${isDark ? 0.25 : 0.05})`,
      }}
    >
      {/* Top row — icon + number */}
      <div className="flex items-start justify-between mb-6">
        <motion.div
          animate={{
            scale:     isActive ? 1 : 0.85,
            boxShadow: isActive ? `0 0 28px ${glow}` : 'none',
          }}
          transition={{ duration: 0.45 }}
          className="w-14 h-14 rounded-2xl flex items-center justify-center"
          style={{
            background: bgAcc,
            border: `1px solid ${isActive ? border : cv(700, 0.15)}`,
          }}
        >
          <motion.div
            animate={{ rotate: isActive ? [0, -8, 8, 0] : 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
          >
            <Icon style={{ width: 24, height: 24 }} className={color} />
          </motion.div>
        </motion.div>

        <span
          className="text-[11px] font-bold tracking-widest px-3 py-1.5 rounded-full"
          style={{
            color:      isActive ? accent : cv(600),
            background: isActive ? bgAcc : cv(800, 0.4),
            border:     `1px solid ${isActive ? border : cv(700, 0.1)}`,
          }}
        >
          {num} / {String(PROBLEMS.length).padStart(2,'0')}
        </span>
      </div>

      {/* Title */}
      <h3 className="text-xl font-bold text-white mb-3 leading-snug">{title}</h3>

      {/* Description */}
      <p className="text-sm text-dark-400 leading-relaxed flex-1">{desc}</p>

      {/* Bottom accent bar */}
      <motion.div
        animate={{ width: isActive ? '100%' : '25%', opacity: isActive ? 1 : 0.3 }}
        transition={{ duration: 0.6, ease: EASE }}
        className="mt-6 h-0.5 rounded-full"
        style={{ background: `linear-gradient(to right,${accent},transparent)` }}
      />
    </motion.div>
  )
}

// ─── Progress indicators ──────────────────────────────────────────────────────
function ProgressBar({ activeIdx, isDark }) {
  return (
    <div className="flex flex-col items-center gap-3 mt-12">
      {/* Dots */}
      <div className="flex items-center gap-2" role="tablist" aria-label="Problem cards">
        {PROBLEMS.map((p, i) => (
          <motion.div
            key={i}
            role="tab"
            aria-selected={i === activeIdx}
            aria-label={`Problem ${i + 1}: ${p.title}`}
            animate={{
              width:      i === activeIdx ? 28 : 8,
              background: i === activeIdx ? p.accent : cv(700, 0.35),
              opacity:    i === activeIdx ? 1 : 0.5,
            }}
            transition={{ duration: 0.35, ease: EASE }}
            className="h-2 rounded-full"
          />
        ))}
      </div>

      {/* Track bar */}
      <div className="w-48 h-px rounded-full" style={{ background: cv(700, 0.2) }}>
        <motion.div
          className="h-full rounded-full"
          animate={{ width: `${((activeIdx + 1) / PROBLEMS.length) * 100}%` }}
          transition={{ duration: 0.4, ease: EASE }}
          style={{ background: `linear-gradient(to right,${PROBLEMS[activeIdx].accent},${PROBLEMS[activeIdx].accent}88)` }}
        />
      </div>

      {/* Scroll hint */}
      <motion.p
        className="text-[11px] text-dark-600 tracking-widest uppercase mt-1"
        animate={{ opacity: activeIdx < PROBLEMS.length - 1 ? 1 : 0 }}
        transition={{ duration: 0.3 }}
        aria-hidden="true"
      >
        scroll to continue ↓
      </motion.p>
    </div>
  )
}

// ─── Vertical fallback (mobile + reduced-motion) ───────────────────────────────
function VerticalCards({ isDark }) {
  return (
    <div className="flex flex-col gap-4 max-w-xl mx-auto px-4">
      {PROBLEMS.map((p, i) => {
        const { Icon, num, title, desc, color, accent, bgAccentD, bgAccentL, borderD, borderL } = p
        const bgAcc = isDark ? bgAccentD : bgAccentL
        const border= isDark ? borderD   : borderL
        return (
          <motion.div
            key={p.title}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: '-30px' }}
            transition={{ duration: 0.5, delay: i * 0.08, ease: EASE }}
            className="flex items-start gap-4 rounded-2xl p-5"
            style={{
              background:     cv(900, 0.7),
              border:         `1px solid ${cv(700, 0.18)}`,
              backdropFilter: 'blur(14px)',
            }}
          >
            <div className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0"
              style={{ background: bgAcc, border: `1px solid ${border}` }}>
              <Icon style={{ width: 18, height: 18 }} className={color} />
            </div>
            <div>
              <p className="text-sm font-semibold text-white mb-1">{title}</p>
              <p className="text-xs text-dark-500 leading-relaxed">{desc}</p>
            </div>
          </motion.div>
        )
      })}
    </div>
  )
}

// ─── Desktop horizontal scroll ────────────────────────────────────────────────
function HorizontalScroll({ isDark }) {
  const sectionRef = useRef(null)
  const [activeIdx, setActiveIdx] = useState(0)

  const { scrollYProgress } = useScroll({
    target:  sectionRef,
    offset:  ['start start', 'end end'],
  })

  // x translation: card 0 → card 5 as scrollYProgress 0 → 1
  const x = useTransform(
    scrollYProgress,
    [0, 1],
    [0, -(PROBLEMS.length - 1) * CARD_STRIDE],
  )

  useMotionValueEvent(scrollYProgress, 'change', (v) => {
    setActiveIdx(Math.min(Math.round(v * (PROBLEMS.length - 1)), PROBLEMS.length - 1))
  })

  const sectionH = `${(PROBLEMS.length - 1) * 100 + 220}vh`

  // live background glow color for active card
  const activeGlow = isDark
    ? PROBLEMS[activeIdx].glowD.replace('0.2)', '0.12)')
    : PROBLEMS[activeIdx].glowL.replace('0.1)', '0.06)')

  return (
    <div ref={sectionRef} style={{ height: sectionH }} className="relative">
      {/* Sticky viewport */}
      <div className="sticky top-0 h-screen overflow-hidden flex flex-col" aria-label="Scroll through problems">

        {/* Dynamic background orb that shifts color with active card */}
        <motion.div
          aria-hidden="true"
          className="absolute rounded-full pointer-events-none"
          animate={{ background: `radial-gradient(circle,${activeGlow} 0%,transparent 70%)` }}
          transition={{ duration: 0.7 }}
          style={{ width: 700, height: 700, top: '15%', left: '50%', translateX: '-50%', zIndex: 0 }}
        />

        <div className="relative flex flex-col flex-1 justify-center" style={{ zIndex: 1 }}>
          {/* Header */}
          <SectionHeader isDark={isDark} />

          {/* Card track */}
          <div className="overflow-hidden" aria-live="polite" aria-atomic="true">
            <motion.div
              style={{
                display:    'flex',
                gap:        CARD_GAP,
                x,
                marginLeft: `calc(50vw - ${CARD_W / 2}px)`,
                willChange: 'transform',
              }}
            >
              {PROBLEMS.map((p, i) => (
                <HorizontalCard
                  key={p.title}
                  problem={p}
                  isActive={i === activeIdx}
                  isDark={isDark}
                />
              ))}
            </motion.div>
          </div>

          {/* Progress */}
          <ProgressBar activeIdx={activeIdx} isDark={isDark} />
        </div>
      </div>
    </div>
  )
}

// ─── ProblemSection ───────────────────────────────────────────────────────────
export default function ProblemSection() {
  const { theme } = useTheme()
  const isDark    = theme === 'dark'
  const reduced   = useReducedMotion()

  return (
    <section
      className="relative overflow-hidden bg-dark-950"
      aria-labelledby="problem-heading"
    >
      {/* Top divider */}
      <div aria-hidden="true" className="absolute top-0 left-1/2 -translate-x-1/2 w-3/4 h-px"
        style={{ background: `linear-gradient(to right,transparent,${
          isDark ? 'rgba(239,68,68,0.25)' : 'rgba(239,68,68,0.15)'
        },transparent)` }} />

      {/* Static background (noise + grid — always shown) */}
      <BackgroundGlow isDark={isDark} accentColor={isDark ? 'rgba(239,68,68,0.07)' : 'rgba(239,68,68,0.04)'} />

      {/* Desktop: horizontal scroll section */}
      {!reduced && (
        <div className="hidden lg:block">
          <HorizontalScroll isDark={isDark} />
        </div>
      )}

      {/* Mobile / reduced-motion: vertical stacked cards */}
      <div className={`${!reduced ? 'lg:hidden' : ''} py-24`}>
        {/* Heading for mobile */}
        <SectionHeader isDark={isDark} />
        <VerticalCards isDark={isDark} />
      </div>

      {/* Bottom divider */}
      <div aria-hidden="true" className="absolute bottom-0 left-1/2 -translate-x-1/2 w-3/4 h-px"
        style={{ background: `linear-gradient(to right,transparent,${
          isDark ? 'rgba(239,68,68,0.18)' : 'rgba(239,68,68,0.1)'
        },transparent)` }} />
    </section>
  )
}
