import { useEffect, useRef, useState } from 'react'
import { motion, useReducedMotion } from 'framer-motion'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import { useTheme } from '../../contexts/ThemeContext'
import {
  AlertTriangle, GitBranch, Shield, Building2,
  TrendingDown, Users,
} from 'lucide-react'

// Register once at module level — safe even if imported multiple times
gsap.registerPlugin(ScrollTrigger)

// ─── helpers ──────────────────────────────────────────────────────────────────
const cv = (n, op = 1) =>
  op < 1 ? `rgb(var(--c-dark-${n}) / ${op})` : `rgb(var(--c-dark-${n}))`

const EASE   = [0.25, 0.4, 0.25, 1]
const CARD_W = 480
const CARD_GAP = 48   // slightly wider gap for breathing room

// ─── Problem data ─────────────────────────────────────────────────────────────
const PROBLEMS = [
  {
    Icon: AlertTriangle, num: '01',
    title: 'Manual Certificate Generation',
    desc:  'Hundreds of certificates generated by hand after every exam cycle, wasting days of staff time with zero scalability.',
    color: 'text-red-400',  accent: '#f87171',
    glowD: 'rgba(239,68,68,0.18)',  glowL: 'rgba(239,68,68,0.09)',
    borderD: 'rgba(239,68,68,0.5)',  borderL: 'rgba(239,68,68,0.3)',
    bgD: 'rgba(239,68,68,0.07)', bgL: 'rgba(239,68,68,0.04)',
  },
  {
    Icon: GitBranch, num: '02',
    title: 'Multiple Disconnected Systems',
    desc:  'Spreadsheets, email threads, and separate tools patched together — no single source of truth, constant data loss.',
    color: 'text-orange-400', accent: '#fb923c',
    glowD: 'rgba(249,115,22,0.18)', glowL: 'rgba(249,115,22,0.09)',
    borderD: 'rgba(249,115,22,0.5)', borderL: 'rgba(249,115,22,0.3)',
    bgD: 'rgba(249,115,22,0.07)', bgL: 'rgba(249,115,22,0.04)',
  },
  {
    Icon: Shield, num: '03',
    title: 'Exam Cheating & Security Risks',
    desc:  'No proctoring, weak session auth, and shared answer keys make every result questionable and legally indefensible.',
    color: 'text-red-500',  accent: '#ef4444',
    glowD: 'rgba(239,68,68,0.18)',  glowL: 'rgba(239,68,68,0.09)',
    borderD: 'rgba(239,68,68,0.5)',  borderL: 'rgba(239,68,68,0.3)',
    bgD: 'rgba(239,68,68,0.07)', bgL: 'rgba(239,68,68,0.04)',
  },
  {
    Icon: Building2, num: '04',
    title: 'No Organization Management',
    desc:  'Cannot manage multiple departments, branches, or client orgs from one platform — every client is a separate headache.',
    color: 'text-amber-400', accent: '#fbbf24',
    glowD: 'rgba(245,158,11,0.18)', glowL: 'rgba(245,158,11,0.09)',
    borderD: 'rgba(245,158,11,0.5)', borderL: 'rgba(245,158,11,0.3)',
    bgD: 'rgba(245,158,11,0.07)', bgL: 'rgba(245,158,11,0.04)',
  },
  {
    Icon: TrendingDown, num: '05',
    title: 'Zero Actionable Analytics',
    desc:  'No visibility into pass rates, score trends, or candidate performance. Decisions made on gut feel, not data.',
    color: 'text-orange-500', accent: '#f97316',
    glowD: 'rgba(249,115,22,0.18)', glowL: 'rgba(249,115,22,0.09)',
    borderD: 'rgba(249,115,22,0.5)', borderL: 'rgba(249,115,22,0.3)',
    bgD: 'rgba(249,115,22,0.07)', bgL: 'rgba(249,115,22,0.04)',
  },
  {
    Icon: Users, num: '06',
    title: 'Poor Candidate Experience',
    desc:  'Confusing registration, delayed results, and zero self-service certificate access drive candidates away for good.',
    color: 'text-red-400',  accent: '#f87171',
    glowD: 'rgba(239,68,68,0.18)',  glowL: 'rgba(239,68,68,0.09)',
    borderD: 'rgba(239,68,68,0.5)',  borderL: 'rgba(239,68,68,0.3)',
    bgD: 'rgba(239,68,68,0.07)', bgL: 'rgba(239,68,68,0.04)',
  },
]

// ─── Heading config ───────────────────────────────────────────────────────────
const HEADING_LINES = [
  ['Managing', ' ', 'Online', ' ', 'Exams'],
  ["Shouldn't", ' ', 'Be', ' ', 'This', ' ', 'Difficult.'],
]
const P_GRAD = new Set(['Online', 'Exams', 'Difficult.'])

const probGradStyle = {
  background: 'linear-gradient(135deg,#fb923c 0%,#ef4444 55%,#dc2626 100%)',
  backgroundSize: '200% 100%',
  WebkitBackgroundClip: 'text',
  WebkitTextFillColor: 'transparent',
  backgroundClip: 'text',
}

// ─── Motion variants ──────────────────────────────────────────────────────────
const charVar = {
  hidden:  { opacity:0, y:16, filter:'blur(4px)' },
  visible: { opacity:1, y:0,  filter:'blur(0px)', transition:{ duration:0.3, ease:EASE } },
}
const headingStagger = {
  hidden:  {},
  visible: { transition:{ staggerChildren:0.022, delayChildren:0.2 } },
}

// ─── SectionBg ────────────────────────────────────────────────────────────────
function SectionBg({ isDark }) {
  const gc = isDark ? 'rgba(239,68,68,0.025)' : 'rgba(239,68,68,0.04)'
  return (
    <div aria-hidden="true" className="absolute inset-0 overflow-hidden pointer-events-none">
      <div className="absolute inset-0" style={{
        backgroundImage:`linear-gradient(${gc} 1px,transparent 1px),linear-gradient(90deg,${gc} 1px,transparent 1px)`,
        backgroundSize:'64px 64px',
      }} />
      <div className="absolute inset-0 opacity-[0.02]" style={{
        backgroundImage:'url("data:image/svg+xml,%3Csvg viewBox=\'0 0 256 256\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'n\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.9\' numOctaves=\'4\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23n)\'/%3E%3C/svg%3E")',
        backgroundSize:'180px 180px',
      }} />
    </div>
  )
}

// ─── SectionHeader ────────────────────────────────────────────────────────────
function SectionHeader({ isDark }) {
  const badge = isDark
    ? { background:'rgba(239,68,68,0.08)', border:'1px solid rgba(239,68,68,0.25)', color:'#fca5a5' }
    : { background:'rgba(239,68,68,0.06)', border:'1px solid rgba(239,68,68,0.2)',  color:'#dc2626' }

  return (
    <div className="text-center mb-8 px-4">
      <motion.div
        initial={{ opacity:0, y:-14, filter:'blur(6px)' }}
        whileInView={{ opacity:1, y:0, filter:'blur(0px)' }}
        viewport={{ once:true }}
        transition={{ duration:0.5, ease:EASE }}
        className="mb-4"
      >
        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-sm font-medium"
          style={{ backdropFilter:'blur(12px)', ...badge }}>
          <AlertTriangle className="w-3.5 h-3.5" />
          <span>Challenges</span>
          <motion.span className="w-1.5 h-1.5 rounded-full bg-red-400"
            animate={{ opacity:[1,0.2,1] }} transition={{ duration:1.4, repeat:Infinity }}
            aria-hidden="true" />
        </div>
      </motion.div>

      <motion.h2 id="problem-heading"
        variants={headingStagger} initial="hidden" whileInView="visible" viewport={{ once:true }}
        className="text-4xl sm:text-5xl lg:text-[50px] font-extrabold leading-[1.1] tracking-tight mb-3 text-white"
      >
        {HEADING_LINES.map((words, li) => (
          <span key={li} className="block">
            {words.map((word, wi) => {
              if (word === ' ')
                return <span key={wi} style={{ display:'inline-block', width:'0.28em' }} aria-hidden="true" />
              if (P_GRAD.has(word)) {
                return (
                  <motion.span key={wi} variants={charVar} style={{ display:'inline-block' }}>
                    <motion.span style={probGradStyle}
                      animate={{ backgroundPosition:['0% 50%','100% 50%','0% 50%'] }}
                      transition={{ duration:5, repeat:Infinity, ease:'linear', delay:li*0.5 }}
                    >{word}</motion.span>
                  </motion.span>
                )
              }
              return (
                <span key={wi} className="inline-block">
                  {word.split('').map((ch, ci) => (
                    <motion.span key={ci} variants={charVar} style={{ display:'inline-block' }}>{ch}</motion.span>
                  ))}
                </span>
              )
            })}
          </span>
        ))}
      </motion.h2>

      <motion.p
        initial={{ opacity:0, y:20, filter:'blur(6px)' }}
        whileInView={{ opacity:1, y:0, filter:'blur(0px)' }}
        viewport={{ once:true }}
        transition={{ duration:0.55, delay:0.4, ease:EASE }}
        className="text-sm text-dark-400 leading-relaxed max-w-lg mx-auto"
      >
        Many organizations still struggle with disconnected tools, manual certificate
        generation, weak security, poor candidate experience, and limited reporting.
      </motion.p>
    </div>
  )
}

// ─── VerticalTrack (left sidebar) ────────────────────────────────────────────
function VerticalTrack({ activeIdx }) {
  return (
    <div aria-hidden="true"
      className="absolute left-8 top-1/2 -translate-y-1/2 hidden xl:flex flex-col gap-3 z-20">
      {PROBLEMS.map((p, i) => (
        <div key={i} className="flex items-center gap-2.5">
          <div
            className="rounded-full transition-all duration-300"
            style={{
              height:     i === activeIdx ? 22 : 8,
              width:      i === activeIdx ? 3  : 2,
              background: i === activeIdx ? p.accent : cv(700, 0.3),
              opacity:    i === activeIdx ? 1 : 0.4,
            }}
          />
          <span
            className="text-[10px] font-semibold tabular-nums transition-all duration-300"
            style={{ color: p.accent, opacity: i === activeIdx ? 0.8 : 0 }}
          >{p.num}</span>
        </div>
      ))}
    </div>
  )
}

// ─── ProgressDots ────────────────────────────────────────────────────────────
function ProgressDots({ activeIdx }) {
  const isLast = activeIdx === PROBLEMS.length - 1
  return (
    <div className="flex flex-col items-center gap-3 mt-6">
      <div className="flex items-center gap-2" role="tablist" aria-label="Problem cards">
        {PROBLEMS.map((p, i) => (
          <div key={i} role="tab" aria-selected={i === activeIdx}
            className="h-2 rounded-full transition-all duration-300"
            style={{
              width:      i === activeIdx ? 28 : 8,
              background: i === activeIdx ? p.accent : cv(700, 0.35),
              opacity:    i === activeIdx ? 1 : 0.45,
            }}
          />
        ))}
      </div>
      <p className="text-[11px] tracking-widest uppercase transition-all duration-300"
        style={{ color: cv(600), opacity: isLast ? 0 : 0.6 }}
        aria-hidden="true"
      >
        {isLast ? 'keep scrolling ↓' : 'scroll to explore ↓'}
      </p>
    </div>
  )
}

// ─── HorizontalCard ───────────────────────────────────────────────────────────
function HorizontalCard({ problem, isActive, isDark }) {
  const { Icon, num, title, desc, color, accent, glowD, glowL, borderD, borderL, bgD, bgL } = problem
  const glow   = isDark ? glowD   : glowL
  const border = isDark ? borderD : borderL
  const bg     = isDark ? bgD     : bgL

  return (
    <motion.div
      animate={{ scale: isActive ? 1 : 0.88, opacity: isActive ? 1 : 0.28 }}
      transition={{ duration: 0.45, ease: EASE }}
      className="shrink-0 flex flex-col rounded-3xl p-8"
      style={{
        width:          CARD_W,
        minHeight:      300,
        background:     isActive ? bg : cv(900, 0.5),
        border:         `1px solid ${isActive ? border : cv(700, 0.1)}`,
        backdropFilter: 'blur(20px)',
        boxShadow:      isActive
          ? `0 24px 80px rgba(0,0,0,${isDark?0.55:0.12}),0 0 60px ${glow},inset 0 1px 0 rgba(255,255,255,${isDark?0.07:0.5})`
          : `0 4px 20px rgba(0,0,0,${isDark?0.15:0.04})`,
      }}
    >
      <div className="flex items-start justify-between mb-6">
        <motion.div
          animate={{ scale: isActive ? 1 : 0.85, boxShadow: isActive ? `0 0 28px ${glow}` : 'none' }}
          transition={{ duration: 0.4 }}
          className="w-14 h-14 rounded-2xl flex items-center justify-center"
          style={{ background: bg, border: `1px solid ${isActive ? border : cv(700, 0.1)}` }}
        >
          <motion.div animate={isActive ? { rotate: [-8, 8, 0] } : { rotate: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}>
            <Icon style={{ width:24, height:24 }} className={color} />
          </motion.div>
        </motion.div>

        <span className="text-[11px] font-bold tracking-widest px-3 py-1.5 rounded-full"
          style={{
            color:      isActive ? accent : cv(600),
            background: isActive ? bg : cv(800, 0.4),
            border:     `1px solid ${isActive ? border : cv(700, 0.08)}`,
          }}>
          {num} / {String(PROBLEMS.length).padStart(2,'0')}
        </span>
      </div>

      <h3 className="text-xl font-bold text-white mb-3 leading-snug">{title}</h3>
      <p className="text-sm text-dark-400 leading-relaxed flex-1">{desc}</p>

      <div
        className="mt-6 h-0.5 rounded-full transition-all duration-500"
        style={{
          width:      isActive ? '100%' : '20%',
          opacity:    isActive ? 1 : 0.2,
          background: `linear-gradient(to right,${accent},transparent)`,
        }}
      />
    </motion.div>
  )
}

// ─── Desktop section — GSAP ScrollTrigger pin ─────────────────────────────────
function DesktopSection({ isDark }) {
  const sectionRef = useRef(null)   // GSAP trigger + pin target
  const trackRef   = useRef(null)   // GSAP translates this
  const [activeIdx, setActiveIdx]   = useState(0)

  useEffect(() => {
    const section = sectionRef.current
    const track   = trackRef.current
    if (!section || !track) return

    // Calculate scroll distance dynamically
    const getScrollDist = () => track.scrollWidth - window.innerWidth

    if (process.env.NODE_ENV !== 'production') {
      console.log('[ProblemSection]', {
        viewportWidth:  window.innerWidth,
        trackWidth:     track.scrollWidth,
        scrollDistance: getScrollDist(),
        sectionHeight:  window.innerHeight + getScrollDist(),
      })
    }

    const ctx = gsap.context(() => {
      gsap.to(track, {
        // Translate exactly by the scroll overflow — first card → last card centered
        x: () => -getScrollDist(),
        ease: 'none',
        scrollTrigger: {
          trigger:           section,
          start:             'top top',
          // end dynamically accounts for any viewport/zoom change
          end:               () => '+=' + getScrollDist(),
          pin:               true,       // pins section in place
          pinSpacing:        true,       // GSAP adds spacer = scrollDist, removes blank gap
          scrub:             1,          // 1s lag for smooth feel
          anticipatePin:     1,          // starts pinning slightly early to avoid flicker
          invalidateOnRefresh: true,     // recalculates x and end on ScrollTrigger.refresh()
          onUpdate: (self) => {
            setActiveIdx(Math.min(
              Math.round(self.progress * (PROBLEMS.length - 1)),
              PROBLEMS.length - 1,
            ))
          },
        },
      })
    }, section)

    // Recalculate on resize/orientation change
    const onResize = () => ScrollTrigger.refresh()
    window.addEventListener('resize', onResize)
    window.addEventListener('orientationchange', onResize)

    return () => {
      ctx.revert()   // kills ScrollTrigger + removes GSAP transforms
      window.removeEventListener('resize', onResize)
      window.removeEventListener('orientationchange', onResize)
    }
  }, [])

  const p = PROBLEMS[activeIdx]
  const accentGlow = isDark
    ? p.glowD.replace('0.18)', '0.1)')
    : p.glowL.replace('0.09)', '0.05)')

  return (
    // NO overflow-hidden here — GSAP needs to position:fixed this element
    // overflow-hidden is only on the inner track wrapper to clip off-screen cards
    <section
      ref={sectionRef}
      aria-labelledby="problem-heading"
      className="relative bg-dark-950"
    >
      {/* Dynamic accent orb — crossfades between card colors */}
      <div
        aria-hidden="true"
        className="absolute inset-0 pointer-events-none transition-all duration-700"
        style={{
          background: `radial-gradient(ellipse 80% 60% at 50% 10%,${accentGlow} 0%,transparent 70%)`,
          zIndex: 0,
        }}
      />

      <SectionBg isDark={isDark} />
      <VerticalTrack activeIdx={activeIdx} />

      {/* Divider top */}
      <div aria-hidden="true" className="absolute top-0 left-1/2 -translate-x-1/2 w-3/4 h-px"
        style={{ background:`linear-gradient(to right,transparent,${isDark?'rgba(239,68,68,0.25)':'rgba(239,68,68,0.15)'},transparent)`, zIndex:10 }} />

      {/* Viewport-height content — this is what the user sees while pinned */}
      <div className="relative h-screen flex flex-col" style={{ zIndex: 1 }}>
        <div className="flex flex-col flex-1 justify-center py-8 min-h-0">
          <SectionHeader isDark={isDark} />

          {/* overflow-hidden ONLY on this wrapper — clips cards that are off-screen */}
          <div className="overflow-hidden">
            <div
              ref={trackRef}
              className="flex items-center"
              style={{
                gap:        CARD_GAP,
                // paddingLeft centers card 1 at x=0
                // paddingRight is INTENTIONALLY removed — browsers exclude trailing
                // flex padding from scrollWidth, causing GSAP to undershoot.
                // A real <div> spacer at the end is included in scrollWidth correctly.
                paddingLeft: `calc(50vw - ${CARD_W / 2}px)`,
                willChange:  'transform',
              }}
            >
              {PROBLEMS.map((prob, i) => (
                <HorizontalCard key={prob.title} problem={prob} isActive={i === activeIdx} isDark={isDark} />
              ))}
              {/* Spacer ensures last card centers: scrollWidth includes this, padding-right would not */}
              <div aria-hidden="true" style={{ width: `calc(50vw - ${CARD_W / 2}px)`, flexShrink: 0 }} />
            </div>
          </div>

          <ProgressDots activeIdx={activeIdx} />
        </div>
      </div>

      {/* Divider bottom */}
      <div aria-hidden="true" className="absolute bottom-0 left-1/2 -translate-x-1/2 w-3/4 h-px"
        style={{ background:`linear-gradient(to right,transparent,${isDark?'rgba(239,68,68,0.18)':'rgba(239,68,68,0.1)'},transparent)`, zIndex:10 }} />
    </section>
  )
}

// ─── Mobile / reduced-motion fallback ─────────────────────────────────────────
function MobileSection({ isDark }) {
  return (
    <section aria-labelledby="problem-heading-m" className="relative bg-dark-950 py-20">
      <SectionBg isDark={isDark} />
      <div className="relative max-w-xl mx-auto px-4" style={{ zIndex: 1 }}>
        <SectionHeader isDark={isDark} />
        <div className="flex flex-col gap-4 mt-2">
          {PROBLEMS.map((p, i) => (
            <motion.div key={p.title}
              initial={{ opacity:0, y:20 }}
              whileInView={{ opacity:1, y:0 }}
              viewport={{ once:true, margin:'-30px' }}
              transition={{ duration:0.45, delay:i*0.07, ease:EASE }}
              className="flex items-start gap-4 rounded-2xl p-5"
              style={{ background:cv(900,0.7), border:`1px solid ${cv(700,0.18)}`, backdropFilter:'blur(14px)' }}
            >
              <div className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0"
                style={{ background:isDark?p.bgD:p.bgL, border:`1px solid ${isDark?p.borderD:p.borderL}` }}>
                <p.Icon style={{ width:18, height:18 }} className={p.color} />
              </div>
              <div>
                <span className="text-sm font-semibold text-white mb-1 block">{p.title}</span>
                <span className="text-xs text-dark-500 leading-relaxed">{p.desc}</span>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  )
}

// ─── ProblemSection ───────────────────────────────────────────────────────────
export default function ProblemSection() {
  const { theme } = useTheme()
  const isDark    = theme === 'dark'
  const reduced   = useReducedMotion()

  return (
    <>
      {/* Desktop: GSAP pin + horizontal scroll */}
      {!reduced && (
        <div className="hidden lg:block">
          <DesktopSection isDark={isDark} />
        </div>
      )}

      {/* Mobile / reduced-motion: vertical stacked */}
      <div className={!reduced ? 'lg:hidden' : ''}>
        <MobileSection isDark={isDark} />
      </div>
    </>
  )
}
